#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 20 10:39:20 2018

@author: rohandayal
"""
from searchtweets import load_credentials, ResultStream, gen_rule_payload, collect_results
import csv
premium_search_args = load_credentials(filename='./secondOAuth.yaml',yaml_key='second_api_auth',env_overwrite=False)
rule = gen_rule_payload("Clinton Overheats -RT",from_date="2016-09-10", to_date = "2016-09-13", results_per_call=100)

#tweets = collect_results(rule, max_results = 100, result_stream_args = premium_search_args)

for tweet in tweets:
    fieldnames = ['text', 'created_at','created_seconds','user_name','retweet_count','favorite_count','hashtags','followER_count','followING_count']
    savefile = open('tweetsAbtRvFDataS20.csv','a')
    thewriter = csv.DictWriter(savefile, fieldnames)
    try:
        thewriter.writerow({'text': tweet.text, 'created_at': tweet.created_at_datetime, 'created_seconds':tweet.created_at_seconds,'user_name':tweet.user_id, 'retweet_count':tweet.retweet_count, 'favorite_count':tweet.favorite_count, 'hashtags':tweet.hashtags, 'followER_count':tweet.follower_count, 'followING_count':tweet.following_count})
    except Exception:
        thewriter.writerow({'text': "unavailable", 'created_at': tweet.created_at_datetime, 'created_seconds':tweet.created_at_seconds,'user_name':tweet.user_id, 'retweet_count':tweet.retweet_count, 'favorite_count':tweet.favorite_count, 'hashtags':tweet.hashtags, 'followER_count':tweet.follower_count, 'followING_count':tweet.following_count})
        print("TEXT IS NOT POSSIBLE")
    savefile.close()
    #print(tweet.split(',"text":"')[1].split(',"source"')[0])
    try:
        print(tweet.text)
        print(tweet.created_at_datetime)
        print(tweet.created_at_seconds)
        print(tweet.user_id)
        print(tweet.retweet_count)
        print(tweet.favorite_count)
        print(tweet.hashtags)
        print(tweet.follower_count)
        print(tweet.following_count)
    except:
        print("Some character cannot be printed")
    """print(tweet.split(',"text":"')[1].split(',"source"')[0])
    print(tweet.split('"created_at":')[1].split(',"id"')[0])
    print(tweet.split('"screen_name":')[1].split(',"location"')[0])"""
    


