#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 26 13:28:45 2018

@author: rohandayal
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

bankdata = pd.read_csv("/Users/rohandayal/IDFinalTweetDataRvF.csv")
#print (bankdata.shape)
#print (bankdata.head)

X = bankdata.drop(['Class', 'Text', 'Date', 'Created_Seconds', 'User_Name', 'Hashtags'], axis=1)#dont include class column or first row
y = bankdata['Class']#Labels for the datapoints
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.30)
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

#scores = cross_val_score(svclassifier, X, y, cv = 10)
y_pred = svclassifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
#print(scores)

